### PR TITLE
Issue 100 - import private copy of inter plugin

### PR DESCRIPTION
**Pull request by thaytan**
The private copy of each element has 'dvs' prepended - pipelines need 'intervideosrc' -> 'dvsintervideosrc' etc.

### CODE REVIEW

**Comment by mithro** [comment]
Why `dvs`?

**Comment by thaytan** [comment]
Brainfart - I thought 'oh, call it after dvswitch -> dvs'. Something based on 'gst-switch' would be better, but I'm not sure what that is

**Comment by mithro** [comment]
It was suggested "gsw" for "gst-switch".

**Comment by thaytan** [comment]
I updated the patch. I'd be careful merging though - autovideoconvert doesn't seem to like the flexible negotiation gwsintervideosrc offers. I'd just use videoconvert instead of autovideoconvert though (and then it works) - autovideoconvert is silly.

**Comment by mithro** [comment]
Lets just do a complete `s/autovideoconvert/videoconvert/` - Do you want me to do it or you?

**Comment by mithro** [comment]
Looks like GstVideoConverter isn't in trusty's gstreamer?
```
gstintervideosrc.c: In function 'gsw_inter_video_src_set_caps':
gstintervideosrc.c:217:3: error: unknown type name 'GstVideoConverter'
   GstVideoConverter *converter;
   ^
gstintervideosrc.c:241:3: error: implicit declaration of function 'gst_video_converter_new' [-Werror=implicit-function-declaration]
   converter = gst_video_converter_new (&black_info, &intervideosrc->info, NULL);
   ^
gstintervideosrc.c:241:13: error: assignment makes pointer from integer without a cast [-Werror]
   converter = gst_video_converter_new (&black_info, &intervideosrc->info, NULL);
             ^
gstintervideosrc.c:242:3: error: implicit declaration of function 'gst_video_converter_frame' [-Werror=implicit-function-declaration]
   gst_video_converter_frame (converter, &src_frame, &dest_frame);
   ^
gstintervideosrc.c:243:3: error: implicit declaration of function 'gst_video_converter_free' [-Werror=implicit-function-declaration]
   gst_video_converter_free (converter);
   ^
cc1: all warnings being treated as errors
```

```
ii  libgstreamer1.0-dev                                   1.2.4-0ubuntu1                                      amd64        GStreamer core development files
```

**Comment by mithro** [comment]
BTW I rebased and squashed your branch at https://github.com/mithro/gst-switch/tree/thaytan-issue-100

**Comment by thaytan** [comment]
Oh. Missing GstVideoConverter is a problem :-/

**Comment by mithro** [comment]
What does GstVideoConverter do?

**Comment by thaytan** [comment]
It's a more-recently-than-1.2 introduced helper class for transforming/generating video frames that lives in libgstvideo.

**Comment by thaytan** [comment]
That is, it helps intervideosrc not have to know about how to generate blank frames in specific formats - the helper class does it.

**Comment by mithro** [comment]
@thaytan - so what our best option here?

**Comment by mithro** [comment]
@thaytan - Friendly poke! Would be really awesome to get this merged.

**Comment by mithro** [comment]
@thaytan Friendly poke :)

I'd really love to get this landed but not sure the best way to import the helper class that is needed.

**Pull request closed without merging**
