### PR TITLE
Run 2to3 Utility on the Python-API-Code

### LINKED ISSUE #139: Python API should support Python 3
- Try running `py2to3` and see what breaks. 
- Check the dependencies support Python 3.

I think we should probably end up with a Python 3 code base and then use `py3to2` to keep support Python 2 support. 

Might want to do https://github.com/timvideos/gst-switch/issues/128 first.

### PR DESCRIPTION
**Pull request by MaZderMind**
The Unit-Tests all pass, Integration-Tests fail atm. because the default Video-Resolution of the Tests of 300x200 does not match the default Server-Resolution of 1280x720 anymore, which is Tracked in #141

Fixes #139

### CODE REVIEW

**Comment by mithro** [comment]
I'd like to continue to support Python 2 too. A couple of projects have been very successful with doing a code base which the Python 2 version is just the Python 3 version converted with 3to2 on the setup.py

**Comment by mithro** [comment]
BTW This seems useful -> http://python-future.org/overview.html

**Comment by mithro** [comment]
I think we want to close this in favour of https://github.com/timvideos/gst-switch/pull/174 from @leesdolphin - Do you agree @MaZderMind ?

**Comment by MaZderMind** [comment]
I still don't see a reason to support python2 if there is no absolute hard dependency requirement, but I'm not the maintainer so feel free to go on.

**Pull request closed without merging**
