### PR TITLE
Ensure input stream is closed on error - addresses issue #95

### PR DESCRIPTION
**Pull request by deeprave**
NOTE: Someone with more experience than I in glib/gobject virtual functions needs to review this to ensure that things are being done correctly. There may be more cases where the gst_worker_close() function should be called, this code handles the specific error case only.

 * Add a "virtual" close function to the gstworker class, call this when error is handled
 * Add a "virtual" close function to the gsocketinputstream class, which ensures that the socket is closed rather than relying on an unref at finalize
 * Add video caps to inputsrc pipeline so that video format errors are detected and handled directly
 * Add a kludge to redirect warnings that are actually errors to the correct handler

### CODE REVIEW

**Comment by mithro** [comment]
Can you take a look at https://github.com/timvideos/gst-switch/pull/124 and then we can rebase this change onto it.

**Comment by deeprave** [comment]
This pull request includes almost the same change, sans the non-empty caps string for audio (which is not actually used).

**Comment by mithro** [comment]
I think this change is missing https://github.com/timvideos/gst-switch/pull/124/files#diff-44f413ac757909c5ec91911a9b12445aR294

**Comment by deeprave** [comment]
Yep, correct - I missed the change to the audioinput src

**Comment by mithro** [comment]
We should rebase this onto https://github.com/timvideos/gst-switch/pull/126 once we are happy with that request.

**Comment by deeprave** [comment]
#126 looks fine, can't see any obvious problems.

**Comment by mithro** [comment]
This looks good now, should I merge?

**Comment by mithro** [comment]
@deeprave can you rebase this onto master so we can merge it?

**Comment by deeprave** [comment]
post rebase, doing tests atm

**Comment by mithro** [comment]
Happy for me to merge it?

**Comment by deeprave** [comment]
Travis says there are still conflicts in tools/gstworker.c, but this should already be fixed in the rebase?

**Comment by mithro** [comment]
Looks like you did a merge rather than a rebase here.

**Comment by deeprave** [comment]
Yep

**Comment by mithro** [comment]
Merged in https://github.com/timvideos/gst-switch/commit/50c55fa2a0c27bc5ec9b235a6e45da4f88ec4be2

**Pull request closed without merging**
