### PR TITLE
Remove Branch-Type Parameter and rename serve to type

### PR DESCRIPTION
**Pull request by MaZderMind**
These are the callback-parameters when adding 4 video sources:

```
parameters=(3003, 1, 7)
parameters=(3004, 1, 8)
parameters=(3005, 1, 10)
parameters=(3006, 1, 10)
```

The second Parameter shows the `GstSwitchServeStreamType` served on that port:
- 1 = GST_SERVE_VIDEO_STREAM
- 2 = GST_SERVE_AUDIO_STREAM

The third Parameter shows the `GstCaseType` serving that port:
- 7 = GST_CASE_BRANCH_VIDEO_A
- 8 = GST_CASE_BRANCH_VIDEO_B
- 10 = GST_CASE_BRANCH_PREVIEW

The latter information is not useful to the client at all and it is only valid until the GUI selects another Video as Source. Therefore I'd suggest to remove that extra Parameter.

From the View of a Client, ie. the GUI, Type is a better name for the Information that Parameter is carrying, so I renamed Serve to Type on the go.

### CODE REVIEW

**Comment by mithro** [comment]
How does the client current figure out which preview videos are active? (IE which preview is connected to channel a, b or the audio output?)

**Comment by MaZderMind** [comment]
As far as I can see there are no methods/signals implemented for this atm, but as far as I can tell there was no such way even before my rewrites. I'll add a callback for that and open a PR.

**Comment by mithro** [comment]
Previously the UI would show red/blue borders around the selected videos.

**Comment by MaZderMind** [comment]
I can't see this behaviour from Code in December. This Feature must have been gone before the start of 2015. I can't see any sign of that in the Code, neither.

Can it be that the UI just selected the Color itsself - without asking the API or waiting for a Callback-Signal?

**Comment by techman83** [comment]
It may have been just in UI, IIRC it didn't really relate to what was occurring in the server as the red borders never disappeared once you clicked the images.

**Pull request closed without merging**
