### PR TITLE
Trying document the pipelines in gstcase{.h,.c}

### PR DESCRIPTION
**Pull request by mithro**
@deeprave - Can you take a look at this?

I'm still trying to figure out why there are a lot more gst-cases then we really need?

### CODE REVIEW

**Comment by mithro** [comment]
@deeprave - You mentioned that a bunch of these cases are not needed - can you elaborate further?

**Comment by deeprave** [comment]
> @deeprave - You mentioned that a bunch of these cases are not needed - can you elaborate further?
> 
> 

Yes it does seem excessive. IIRC (and I haven't looked at the code for the last couple weeks) only the input sources for audio/video and branch cases were actually useful. The (non-branch) preview one is assigned if comp_a and comb_b were already assigned but I struggled to understand if this could actually happen in practice and whether an error would be more appropriate should this happen rather than blandly assigning it as non-branch/composite preview audio or video. There are also some (at least 1 anyway) gstworker/gstcase instances that are created on startup but never used that make the code look like the gstcase enums are in fact useful, but they are not.  Removing these would eliminate code, and the pipelines they used do not even make use of the gstcase pipeline switch.

Sorry, not a lot of time before I start travelling and won't get a lot of coding time anytime soon, but I'll see what I can do in early March if I get bored while on vacation (and I probably will). Should have regular internet access then.

Cheers,
David

**Comment by MaZderMind** [comment]
The preview-Branch seems to be used when a third Video-Source is connected which needs to be passed to the UI for preview. I found that while working on #190. When attaching 4 Video-Sources, I get the following signals in the UI:
````
parameters=(3003, 1, 7)
parameters=(3004, 1, 8)
parameters=(3005, 1, 10)
parameters=(3006, 1, 10)
````

The fourth Parameter is the GstCaseType that emited the signal, where
 - 7 = GST_CASE_BRANCH_VIDEO_A
 - 8 = GST_CASE_BRANCH_VIDEO_B
 - 10 = GST_CASE_BRANCH_PREVIEW

**Comment by deeprave** [comment]
> The preview-Branch seems to be used when a third Video-Source is connected which needs to be passed to the UI for preview. I found that while working on #190 <https://github.com/timvideos/gst-switch/pull/190>. When attaching 4 Video-Sources, I get the following signals in the UI:
> parameters=(3003, 1, 7)
> parameters=(3004, 1, 8)
> parameters=(3005, 1, 10)
> parameters=(3006, 1, 10)
> The fourth Parameter is the GstCaseType that emited the signal, where
> 
> 7 = GST_CASE_BRANCH_VIDEO_A
> 8 = GST_CASE_BRANCH_VIDEO_B
> 10 = GST_CASE_BRANCH_PREVIEW

I was not referring to the branch preview case, but the non-branch one, IE GST_CASE_PREVIEW.

Cheers,
David

**Comment by MaZderMind** [comment]
Oh okay, I missed that one.

**Comment by duzy** [comment]
Hi remember that all inputs are actually dynamic, meaning that the source
switching cases with streams are created as new connections are coming. And
before any connection was sending any byte, an initial framework of
pipelines has to be established in order to make things ready to go.

And actually all stream cases were being used, either as previews or as
main composite a/b. Note that when a stream was selected as being a
composite source, it's still being branched to the preview.

Once the input connection was broken, the corresponding cases would be
erased. I remember that there's also a way from the ui to disconnect a
input (might need to be confirmed).

It shouldn't have any running cases being wasted, unless something leaks.
And the design diagram should be well presenting the framework of pipelines
in the code, everything in the diagram could have something matching in the
code. So it should be much easier checking the diagram while reading the
code.

I hope this information would help. I'm sorry I can't check gstswitch list
too often due to the daily busy live. But I hope that I could have more
time to offer help on this in the future when I get back to freelance.

Cheers,
Duzy Chan

**Pull request closed without merging**
