### PR TITLE
Fixing the `python-api/tests/integrationtests`

### PR DESCRIPTION
**Pull request by mithro**
Fixes https://github.com/timvideos/gst-switch/issues/141

All the tests currently pass on my local computer, however they seem to be flaky on travis. Trying to figure out what is going on there. https://travis-ci.org/mithro/gst-switch/builds/47419942

### CODE REVIEW

**Comment by mithro** [comment]
@MaZderMind, @hyades and @leesdolphin - Can you give this a try and see if they fail on your local machine too?

**Comment by hyades** [comment]
@mithro runs fine on my machine too!

**Comment by MaZderMind** [comment]
For the integration-tests:
````
===== 18 passed, 5 skipped, 1 xfailed, 2 warnings in 65.56 seconds =====
mv: cannot stat ‘htmlcov/*.*’: No such file or directory
Makefile:34: recipe for target 'integration' failed
make: [integration] Error 1 (ignored)
rm imgurbash.sh*
````

**Comment by leesdolphin** [comment]
@MaZderMind I get the same problems on my computer; but apart from that it builds successfully.

**Comment by mithro** [comment]
BTW The `mv: cannot stat ‘htmlcov/*.*’: No such file or directory` error should be fixed now.

**Comment by MaZderMind** [comment]
loogs good to me, go on and merge.

**Comment by mithro** [comment]
Sadly, they still fail on travis sporadically but I think it is going to take a rewrite before they are properly fixed there.

Merging.

**Pull request merged**
